buildscript {
    repositories {
        maven {
            name = "Forge"
            url = "https://maven.minecraftforge.net/"
        }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:6.0.46'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

group = 'dev.maximerix.tuffblocks'
version = '1.2-1.20.6'
archivesBaseName = 'TuffBlocks'

jar {
    archiveBaseName.set("TuffBlocks")
    archiveVersion.set("${version}")
    archiveClassifier.set('DEV')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net/"
    }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.6-50.2.0'
}

minecraft {
    mappings channel: 'official', version: '1.20.6'
    reobf = false
    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                tuffblocks {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                tuffblocks {
                    source sourceSets.main
                }
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
