modLoader="javafml"
loaderVersion="[28,32,)"
license="MIT"

[[mods]]
modId="tuff"
version="1.2-1.15.2"
displayName="TuffBlocks"
updateJSONURL="https://raw.githubusercontent.com/MaximeriX/TuffBlocks/refs/heads/main/update.json"
displayURL="https://maximerix.dev/tuffblocks"
logoFile="logo.png"
credits="MaximeriX"
authors="MaximeriX"
description="Adds tuff blocks from 1.21 to older versions"

[[dependencies.tuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.15.2]"
    ordering="NONE"
    side="BOTH"