modLoader="javafml"
loaderVersion="[36,38,)"
license="MIT License"

[[mods]]
modId="tuff"
version="1.0.8-1.17.1"
displayName="TuffBlocks"
credits="MaximeriX, Mojang AB"
displayURL="https://curseforge.com/minecraft/mc-mods/tuffblocks"
updateJSONURL="https://pastebin.com/raw/xh0jwySd"
logoFile="logo.png"
authors="MaximeriX"
description="Adds tuff blocks from 1.21 to older versions"

[[dependencies.tuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.17.1]"
    ordering="NONE"
    side="BOTH"




